project:
  type: website
  output-dir: docs

website:
  sidebar:
    title: "COMP1711 - Procedural Programming" 
    style: docked
    contents: 
      - section: Notes
        contents: Notes/*
      - section: Exercises
        contents: Exercises/*
  # body-header: |
  #  {{< video https://www.youtube.com/watch?v=fXCUaRE-5Rc >}}


format:
  html:
    theme: flatly
    css: styles.css
    toc: true