---
title: "1: Linux Command line skills"
---

# Exercise 1
1. Create the following directory tree in the shell training repo: 

> `work`  
`work/input_data/`  
`work/results/`  
`work/program/`  

2. Create the file `input.txt` with a text editor and put some text in it.

3. Move the file to `work/input_data` and rename it in the same command to `control01.txt`

4. Create this directory tree in one line only: `work/experiment/results/report` 

5. Delete the `work` directory and all of its contents with one single command.

::: {.callout-tip}
Use the man command to check the options that you can use to do these last two tasks.
:::

# Exercise 2
Let’s introduce two new commands:

* The `sort` command will sort lines alphabetically (or numerically...)
* the `cut` command to split lines of text based on a given character e.g. `cut -d ',' -f 2` will split lines around the comma and give you the second part

Combine `cat`, `cut`, and `sort` in a bash script to print out the Latin names from `birds.txt` in alphabetical order.

Save the output to a new file.

## Extension

* Edit the script to combine the latin names from all of the animal files in alphabetical order. (may find issues with spaces in the front of the names - try to google how to fix this)
* Now try and make it in a single line. 

## Answers - out of date
`cat IOM-animals/birds.txt  | cut -d ',' -f 2 | sort > orderedBirds.txt`

`cat IOM-animals/*.txt  | cut -d ',' -f 2 | awk '{$1=$1;print}' |sort > orderedAnimals.txt`

# Exercise 3
shell-training/data/ contains 300 data files, each of which should contain 100 values. One of these files is missing some data though...

Use a series of commands connected by pipes to identify the file with missing data (hint `wc -w` will tell you the number of values in a file, `sort -n` will sort numerically)

## Answer
`wc -w data/* | sort -n`

# Exercise 4
Use the `sed` command to delete the first character and last character in each line of a file (any file, you create it)Use the sed command to delete the first character and last character in each line of a file (any file, you create it).

You must research the `sed` command for this exercise.

## Answer
`sed 's/^.//' IOM-animals/birds.txt | sed 's/.$//'`