---
title: "4: Introduction to C"
---

:::{.callout-important}
Instructions in this file are to be run in the same codespace based on 1711-introduction. Make sure to save your changes.
:::

# Aims
- Understand basic C ?? - needs more details!! 

# History

Originating as an improvement to the B programming language by Dennis Ritchie started in 1971, C is a low level procedural programming language. Through its early development C looked very different to the language that you will learn in this module.

The first standard of the language that is close to modern C wasn't formalised until the late 1980s. This version was first recognised by American National Standards Institute (ANSI) in 1989 and later International Organization for Standardization (ISO) in 1990. This version is often referred to by acronyms of the organisations that recognised it or the year in which it was recognised (C89/C90)

There have been revisions to the language since but changes in these updates are minor. This is where the main challenge in C comes from; it's simple without the programming shortcuts and quality of life improvements found in modern high-level languages. This leaving the programmer doing lots of the heavy lifting.

# Why C?

Get Martin to write this

# "Hello, world!"
This program is a de-facto standard for the first program you will see in any language. It stands as an effective tool to cover the basics of a language.

We will break it down to show you some basics of C

`hello-world.c`
``` c
#include <stdio.h>
int main()
{
   // This is a comment. 
   // The next line of this program is for output
   printf("Hello, World!");
   return 0;
}
```    

## Breakdown 
* `#include` is a preprocessor command that allows a c program to use functionality that is implemented in separate c files. More detail will be given on this later in the course

* `int main()` is the entrypoint of a c program, every c program you write will include this i.e. the first line of code run is the first line within the `{}` of main.

* The `//` marks the start of a single line comment, this part of the code is for notes from/to developers and does not affect the functionality of the program.

* As the comment mentions, `printf()` is used to output to the command line.

* The `return` statement sends a status value back to the command line, a 0 status suggest a successful execution.

# How to run this
Programs in c must be compiled and executed separately. These steps are almost always taking place when running code but are sometimes abstracted to a single run button in an IDE.

## The C compiler
The most common c compiler across unix machines is gcc. At its most simple for our use it can simply be run like this:
``` bash
gcc hello-world.c
```
This will produce a output executable called `a.out` that can be run like this:
```default
$ ./a.out
Hello, world!
```
Here you can see that the `./` syntax for running the executable is the same as for an executable shell script when the executable is in your directory.

This output file can be renamed using the `-o` option to specify an output file for the compiler e.g. to create an executable with the same name (but no extension): `gcc hello-world.c -o hello-world`

# Syntax and Keywords
* Syntax 
    - Like the punctuation of a programming language, describes the required structure for the code to be acceptable.
    - Most important piece of syntax in C is every line ends with a `;`
* Keywords 
    - Terms that relate to a  specific instruction in the programming language
    - Key examples in this program: `int` and `return`

# Variables
## Key parts
A variable made up of 3 things

1. An identifier used in the code to refer to a stored value
2. The location in memory where this data is being stored
3. The data type which is used to specify the way this data should be stored and accessed.

## Data types
There are 2 key basic data types in C:

- `int` used to store integer numbers 
- `float` used to store floating point (decimal) numbers
- `char` used to store characters  
    - In C characters are stored as 'ASCII' values and each one can be converted to their integer value [see this table](https://www.rapidtables.com/code/text/ascii-table.html)

There are also further data types used to store numbers, these are adapted to increase the range of values possible to store or the precision with which they can be stored.

All data types are keywords in the C language. 

## Using variables in C

There are three key actions that can be taken with variables

* Initialization - in C this defines the variables identifier and data type and will trigger the system to assign a portion of memory to it. e.g.
    * `int counter;`
* Assignment - This alters the value of the variable stored in memory. e.g.
    * `counter = 2;`
    * The value that is being assigned can be simply typed in code or the result of an arithmetic calculation
    * These first two steps can be combined into a single line: `int counter = 2;`
* Access - Use of the variable using the identifier in code, this can be in any statement where a value of that data type is required e.g. creating a new variable: `int newCounter = counter + 2;`

# Reading Input
Lets customize the hello world program to say hello to you. We can use a variable and `scanf()` to do this.

`hello-you.c`
``` c
#include <stdio.h>
int main()
{
    char name [20];
    printf("Please enter your name: ");
    scanf("%s", name);
    printf("Hello, %s!\n", name);
    return 0;
}
```
### Breakdown 
* The first new line in main initializes an array with identifier `name` and size 20
    - this is a special case of a variable with a single identifier allowing for access to multiple values on a single data type stored continuously. More info will be in later notes.
- The next line outputs similarly to out original hello world program.
- `scanf()` is used to read input from the command line. Within the brackets there are 2 input arguments.
    - `"%s"` specifies that the input will be read as a string - a special case of a character array.
    - `name` specifies the variable that the data should be stored in.
- The usage of `printf()` in the line after is altered compared to the first program:
    - First the `%s` is again used to specify the string, but this time for output. These patterns starting with a `%`, using different letters for different data types, are known as format specifiers and are used across input and output.
    - `\n` is the character representing a newline, improving the output format.
    - `name` specifies which variable to output the data from
    - For each format specifier in a `printf` string the language expects a variable of the appropriate type to pull data from to output

# Arithmetic
The values that are stored in your variables are not always the values that you want to use in your code. In C we can manipulate numeric values with arithmetic operators. 

Here is a simple program to show the different arithmetic operators. You should run this yourself to see the results.

`arithmetic.c`
``` c
#include <stdio.h>

int main()
{
    const int value = 12;
    printf("Your value + 3 = %d\n", value + 3);
    printf("Your value - 3 = %d\n", value - 3);
    printf("Your value * 3 = %d\n", value * 3);
    printf("Your value / 3 = %d\n", value / 3);
    printf("Your value modulo 3 = %d\n", value % 3);
}
```
## Operator precedence (TODO) 


## Notes
- This program uses the keyword `const` to modify the data type of the variable `value`. This stops the variable from being changed later in the program.
    - Using a static value like this is good for the program as it means that in the code there is only a single place where the value needs to be changed. This makes the code more maintainable.

## Casting 
Casting is the process of taking a variable of one data type and changing it to a value with a different data type, sometimes this happens implicitly and other times you have to be very specific.

``` c
#include <stdio.h>

int main()
{
    int number1 = 123, number2 = 12;

    // seccond format specifier will cast from int to character
    printf("Succesful cast of integer (%d) to character: %c\n", number1, number1);

    // This will read a float from the resut of the division of two integers
    // The value will be a float but also a whole nubmer
    float output =  number1/number2;
    printf("Failed cast from float to integer: %f\n", output);

    // In this cast the value is cast before the operation and therefore the 
    // program mputation calculates using floating point arithmetic
    output = number1/(float)number2;
    printf("Successful cast from float to integer: %f\n", output);
}
```

In general you can cast from:
- character to int
- int to float
- float to double
Without having to worry about losing information.


# Control flow
Control flow is the process by which the program selects what line should be run next there are different ways to do this:

## Sequential
This is the most simple way and the default, you simply proceed to the next line after each line, as such there are no special structures associated with it.

## Logical expressions
More complex control flow will always require evaluating conditions to make a decision. This is achieved in C using logical expressions. Logical expressions are built from comparisons and logical operators; these either act on static values of variables or a combination. N.B. these can also implement arithmetic operators in combination with this.

### Examples of logical expressions
`counter <= 12`  
`value > threshold || override == 1`  
Eventually you will need to use more complex statements
``` c
source->metaData[WIDTH] + colStartIndex  > destination->metaData[WIDTH] || source->metaData[HEIGHT] + rowStartIndex > destination->metaData[HEIGHT]
```

## Branching 
In branching control flow a selection is made between different segments of code based on a variable or logical expression. The most commonly used branching pattern is the if-else statement:
```c
if(/*Logical Expression*/)
{
    // code run if logical expression is true
}
else
{
    // run code 
}
```
- Additionally `else if` statements can be added to have additional arguments to control when a block of code is run. 
    - Code within an `else if` block will only run if the conditions for the parent if statement and any previous if conditions are all not met.
- Code within an `else` block are only run if none of the conditions are met
- An `if` statement does not require any subsequent `else` statements.

### Example
Test this out for yourself!

`numbers.c`
``` c
#include <stdio.h>
int main()
{
    int num = 0;
    printf("Please enter a number: ");
    scanf("%d", &num);
    if (num > 10)
    {
        printf("Your number is greater than ten.\n");
    }
    else if (num < 0)
    {
        printf ("Your number is less than 0\n");
    }
    else
    {
        printf ("Your number is between 0 and 10 (inclusive)\n");
    }
    return 0;
}
```
#### Notes
- Note that the `%d` format specifier is used to read an integer
- The `&` symbol is required in front of not array variables when using `scanf()`.

## Looping
In looping control flow segments of code are executed repeatedly either based on a logical expression (while loop) or for a specific number of loops (for loop).

### While loop
``` c
while(/*logical expression*/)
{
    // code to be run
}
```
The logical expression is evaluated before each time the codeblock is run, making it possible to run the code 0 times. 

#### Example
`average.c`
``` c
#include <stdio.h>
int main()
{
    int counter = 0;
    float input = 0, total = 0; 
    printf("This is a program to calculate the average of positive values.\n")
    printf("Once you have entered all your values enter a negative number to calculate the average.\n");
    while (input != -1)
    {
        printf("Enter value:");
        scanf("%f", &input);
        if (input < 0)
        {
            continue;
        }
        counter += 1;
        total += input;
    }
    printf("Average is %f\n", total/(float)counter);
}
```
##### Breakdown
- Multiple variables of the same kind can be initialised in a single line when separated with commas.
- `%f` format specifier for floats
- The `continue` keyword causes the current iteration of the loop to end and the next one to start.
- Any control structure can be nested within another control structure.

### For loop
`for-test.c`
``` c
#include <stdio.h>
int main()
{
    for (int i = 0; i < 5; i++) // Example loop to run 5 times.
    {
        // Code to be run
        printf("(%d)\n", i);
    }
}
```
#### Breakdown
The for loop control code has 3 key parts:

1. Variable initialisation and assignment.
    - In this example:`int i = 0;`
    - It is typical in C (and may other programming languages) to start counting from 0, therefore it is often useful to start a loop control variable from 0.
    - The identifier `i` is used as a de-facto standard but can be renamed to improve code readability.

2. Condition.
    - In this example: `i < 5`
    - The code within the loop will run while this condition is true.
    - As such be careful if a mistake is made in the condition it may prohibit the code within the loop from running.

3. Updating the variable
    - In this example: `i++
    - `++` is called the increment operator and simply increases the value of a variable by one. It is simply a shortening of the code `x = x+1`.
    - `--` (the decrement operator) is often used in place of `++` for decreasing loops.
    - Can also use `i += <val>` or `i -= <val>` to change variable by more than one without referencing it twice.

You should run `for-test.c` to check that this is all true. You can then change the parameters to see the values of i for which the loop will be run. Change the parameters so that it runs for different values:

- Values from 7 to 14
- Only even numbers to 12
- Decreasing values from 4 to 0

#### Example
What do you think this block of code will do? Run it to find out!
`pattern.c`
``` c
#include <stdio.h>
int main()
{
    for(int i = 1; i < 8; i++)
    {
        for(int j = 0; j < i; j++)
        {
            printf("*");
        }
        printf("\n");
    }
}
```

##### Notes
- Nested for loops are a common pattern. You have to make sure to use different variables for the inner and outer loops.
- In this case the inner loop is dependent on the outer loop as the condition for the inner loop is  based on the control value of the outer loop

### Break and continue 
`break` and `continue` are two keywords in C that can be used to control the program flow when using loops.

`continue` will cause the current running loop to skip to the end and start the next loop. That is the next piece of code to be evaluated is the loop control. 

`break` will cause the current loop section to exit. That is the next line of code that will run is the first line after the loop the code is currently in.

<!-- May be worth including information about how it is often better to change the loop conditions than to use these keywords -->

# Scope (What is {})
Scope is the area of a code file where a variable can be referenced; variables can be accessed in any child scope of the scope in which they are defined. In C `{}` always defines a scope for whatever keyword it is related to. You can also define a scope without a keyword.

# Best practice in C

## Whitespace
All of the examples featured so far follow traditional beat practice for the use of whitespace. 

- New line after each semi-colon
- Code within a Scope is indented. Code within a subscope is indented for each parent scope
    - The size of indents is cause for debate, the approach that we have chosen is 4 space sized indents. Though tabs are traditionally 8 characters wide.

## Comments
All of the code in these examples has been simple and short, however, as code becomes longer it becomes exponentially more difficult to comprehend. Comments should be used to make your code more understandable describing high level aims of the code or why a specific approach has been used rather than simply explaining the syntax of the code that is there.

# Notes
* outline what happens in a basic hello world file & compiler
* external libraries
* syntax of variable declaration and assignment
* basic IO
* program flow & syntax
    * if/else
    * looping

- scope!
- arithmetic

# Operator appendix

## Arithmetic
| Operator | Name |
|---|---|
| `+` | Addition |
| `-` | Subtraction |
| `*` | Multiplication |
| `/` | Division |
| `%` | Modulo (remainder after division) |

## Comparison
| Operator | Name |
|---|---|
| `==` | Equal to |
| `!=` | Note equal to |
| `>` | Greater than |
| `<` | Less than |
| `<=` | Less than or equal to |
| `>=` | Greater than or equal to |

## Logical
| Operator | Name |
|---|---|
| `&&` | AND |
| `||` | OR |
| `!` | NOT|
