---
title: TODO
---

# Reminders
- Accessibility
- Aims at the start of each section
- Update examples as template changes

# Missiong parts
- Microbit examples and exercises

# C exersizes

- alter the patterns.c

#  C notes 2
- functions
    - contextualise using control flow
- parameter passing

# C notes 3
- arrays
    - Dimensions
    - looping over
    - mention pointers
- strings
    - special case of character array
    - `\0`

# C notes 4
- pointers 
- memory allocation
    - malloc
    - free
    - calloc??

# C notes 5
- Strucutres
- file IO

# C notes 6
- linked lists

# C notes 7
- stacks and queues

# C notes 8
- trees

# C notes 9
- search & sort 

# Review
- A lot of the more complex ideas with the microbit essentially will require either creating an event handler or using the one built into the library,  I have yet to fully explore this so have not included it in the notes yet. I am also not sure if the extra complexity is worth it given I'm still unsure of the complexity of the microbit tasks the students will be assigned.

